//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 08:10:39 PM MSK
//


package by.javatr.task4.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="temperature" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="photophilious" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="watering" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "growing_tips")
public class GrowingTips {

    @XmlElement(required = true, defaultValue = "22")
    @XmlSchemaType(name = "positiveInteger")
    protected int temperature;
    @XmlElement(defaultValue = "true")
    protected boolean photophilious;
    @XmlElement(required = true, defaultValue = "100")
    @XmlSchemaType(name = "positiveInteger")
    protected int watering;

    /**
     * Gets the value of the temperature property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getTemperature() {
        return temperature;
    }

    /**
     * Sets the value of the temperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTemperature(int value) {
        this.temperature = value;
    }

    /**
     * Gets the value of the photophilious property.
     * 
     */
    public boolean isPhotophilious() {
        return photophilious;
    }

    /**
     * Sets the value of the photophilious property.
     * 
     */
    public void setPhotophilious(boolean value) {
        this.photophilious = value;
    }

    /**
     * Gets the value of the watering property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getWatering() {
        return watering;
    }

    /**
     * Sets the value of the watering property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWatering(int value) {
        this.watering = value;
    }

}
