//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 08:10:39 PM MSK
//


package by.javatr.task4.entity;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for multiplyingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="multiplyingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="seeds"/>
 *     &lt;enumeration value="leafs"/>
 *     &lt;enumeration value="stalks"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "multiplyingType")
@XmlEnum
public enum MultiplyingType {

    @XmlEnumValue("seeds")
    SEEDS("seeds"),
    @XmlEnumValue("leafs")
    LEAFS("leafs"),
    @XmlEnumValue("stalks")
    STALKS("stalks");
    private final String value;

    MultiplyingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MultiplyingType fromValue(String v) {
        for (MultiplyingType c: MultiplyingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
