//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 08:10:39 PM MSK
//


package by.javatr.task4.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for soilType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="soilType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="podzolic"/>
 *     &lt;enumeration value="ground"/>
 *     &lt;enumeration value="sod-podzolic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "soilType")
@XmlEnum
public enum SoilType {

    @XmlEnumValue("podzolic")
    PODZOLIC("podzolic"),
    @XmlEnumValue("ground")
    GROUND("ground"),
    @XmlEnumValue("sod-podzolic")
    SOD_PODZOLIC("sod-podzolic");
    private final String value;

    SoilType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SoilType fromValue(String v) {
        for (SoilType c: SoilType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
