//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.24 at 08:10:39 PM MSK
//
package by.javatr.task4.entity;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="stalk_color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="leaf_color" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="flower_size" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "visual_param")
public class VisualParam {

    @XmlElement(name = "stalk_color", required = true, defaultValue = "green")
    protected String stalkColor;
    @XmlElement(name = "leaf_color", required = true, defaultValue = "green")
    protected String leafColor;
    @XmlElement(name = "flower_size", required = true, defaultValue = "1")
    @XmlSchemaType(name = "positiveInteger")
    protected Integer flowerSize;

    /**
     * Gets the value of the stalkColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStalkColor() {
        return stalkColor;
    }

    /**
     * Sets the value of the stalkColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStalkColor(String value) {
        this.stalkColor = value;
    }

    /**
     * Gets the value of the leafColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeafColor() {
        return leafColor;
    }

    /**
     * Sets the value of the leafColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeafColor(String value) {
        this.leafColor = value;
    }

    /**
     * Gets the value of the flowerSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getFlowerSize() {
        return flowerSize;
    }

    /**
     * Sets the value of the flowerSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFlowerSize(int value) {
        this.flowerSize = value;
    }

}
